name: IT-Tools
version: 2024.10.22-7ca5933
stage: stable
slug: it-tools
description: "Collection of handy online tools for developers, with great UX"
url: https://github.com/CorentinTh/it-tools
arch:
  - amd64
  - aarch64
startup: services
boot: auto
host_network: false
ports:
  "8080/tcp": 8080
image: corentinth/it-tools