name: Memos
version: 0.25.3
stage: experimental
slug: memos
description: Self‑hosted note‑taking service.
url: https://github.com/usememos/memos
arch:
  - amd64
  - aarch64
startup: services
boot: auto
host_network: false
ingress: true
ingress_port: 8080
environment:
  MEMOS_PORT: "8080"
  MEMOS_DATA_DIR: /share/memos
image: neosmemo/memos