name: Memos
version: 0.25.3
stage: stable
slug: memos
description: "An open-source, self-hosted note-taking service"
url: https://github.com/usememos/memos
arch:
  - amd64
  - aarch64
startup: services
boot: auto
host_network: false
ingress: false
# ingress_port: 5230
ports:
  "5230/tcp": 5230
environment:
  MEMOS_MODE: "prod"
  MEMOS_PORT: "5230"
  MEMOS_ADDR: "0.0.0.0"
  MEMOS_DATA: "/share"
map:
  - type: share
    read_only: False
image: neosmemo/memos