name: Memos
version: 0.25.3
stage: experimental
slug: memos
description: "Self‑hosted note‑taking service"
url: https://github.com/usememos/memos
arch:
  - amd64
  - aarch64
startup: services
boot: auto
host_network: false
ingress: true
ingress_port: 8080
ingress_entry: /
ports:
  "8081/tcp": 8081
environment:
  MEMOS_MODE: prod
  MEMOS_PORT: 8081
  MEMOS_ADDR: 0.0.0.0
  MEMOS_DATA: /share/memos
image: neosmemo/memos