name: Memos
version: 0.25.3
stage: experimental
slug: memos
description: "Self‑hosted note‑taking service"
url: https://github.com/usememos/memos
arch:
  - amd64
  - aarch64
startup: services
boot: auto
host_network: false
ingress: true
ingress_port: 5230
ports:
  "5230/tcp": 5230
environment:
  MEMOS_MODE: "prod"
  MEMOS_PORT: "5230"
  MEMOS_ADDR: "0.0.0.0"
  MEMOS_DATA: "/share/memos"
image: neosmemo/memos